#ifndef RETURN_STATUS_H
#define RETURN_STATUS_H


typedef enum {
  INVALID_GET_MEMORY = -5,
  INVALID_SYSTEM_DIGIT = -4,
  INVALID_ZECKENDORF_NUMBER = -3,
  INVALID_ROMAN_DIGIT = -2,
  INVALID_ROMAN_NUMERAL = -1,
  OK = 0
} returnStatus;


#endif
